language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 6

after_success:
  - bash <(curl -s https://codecov.io/bash)

 # cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
